@startuml As-Is_Simple

title **As-Is: Ручной процесс записи на мероприятие**

start
:Преподаватель объявляет\nо мероприятии (чат / устно);

:Студенты пишут в чат\n"Я приду", "Я тоже"\nили подходят лично;
note right
  **Узкое место 3:**
  Потеря информации
  **Узкое место 6:**
  Затраты времени
end note

:Преподаватель вручную\nсобирает и просматривает заявки;
note right
  **Узкое место 1:**
  Высокая трудоемкость
  для преподавателя
  **Узкое место 6:**
  Затраты времени
end note

if (Все желающие\nвмещаются?) then (Нет)
    :Разрешить конфликты\n(переписка, споры);
    note right
      **Узкое место 5:**
      Конфликтность
      **Узкое место 6:**
      Затраты времени
    end note
else (Да)
endif

:Преподаватель вручную\nформирует итоговый список;
note right
  **Узкое место 1:**
  Высокая трудоемкость
  для преподавателя
  **Узкое место 2:** 
  Отсутсиве прозрачности
  **Узкое место 4:**
  Ошибки в учёте
  **Узкое место 6:**
  Затраты времени
end note

:Преподаватель напоминает\nо времени и месте;
note right
  **Узкое место 3:**
  Потеря информации
  **Узкое место 6:**
  Затраты времени
end note

:Студенты приходят\nна мероприятие;
stop

@enduml